### ISSUE TITLE
@pnp/sp not work with spfx 1.12.1

### ISSUE THREAD

**Issue by quantrpeter** [pnp/pnpjs#1780]
Hi
   after execute:
```

import { sp } from "@pnp/sp/presets/all";

    sp.setup({
      spfxContext: this.context
    });
    const listEnsureResult = await sp.web.lists.ensure(listName);
```

i got:
```
invokable-binder.js:17 Uncaught (in promise) TypeError: Object(...) is not a function
    at factory (invokable-binder.js:17)
    at applyFactoryExtensions (invokable-extensions.js:86)
    at invokable-binder.js:26
    at index.js:10
    at SPRest.9l4K.SPRest.childConfigHook (rest.js:67)
    at SPRest.get [as web] (index.js:8)
    at ShortcutWebPart.<anonymous> (ShortcutWebPart.ts:59)
    at step (shortcut-web-part_4d5a73f77f6328336074.js:2633)
    at Object.next (shortcut-web-part_4d5a73f77f6328336074.js:2614)
    at shortcut-web-part_4d5a73f77f6328336074.js:2608
```

package.json:
```
{
  "name": "methodist-intranet",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@microsoft/decorators": "1.12.1",
    "@microsoft/sp-application-base": "1.12.1",
    "@microsoft/sp-core-library": "1.12.1",
    "@microsoft/sp-dialog": "1.12.1",
    "@pnp/sp": "^2.5.0",
    "bootstrap": "^4.6.0",
    "classnames": "^2.3.1",
    "jquery": "^3.6.0",
    "moment": "^2.29.1",
    "react-bootstrap": "^1.6.0",
    "react-modal": "^3.13.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.12.1",
    "@microsoft/sp-tslint-rules": "1.12.1",
    "@microsoft/sp-module-interfaces": "1.12.1",
    "@microsoft/sp-webpart-workbench": "1.12.1",
    "@microsoft/rush-stack-compiler-3.7": "0.2.3",
    "gulp": "~4.0.2",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1"
  }
}
```

thanks
Peter

**Comment by patrick-rodgers** [comment]
You skipped all the details we request in the issue template. Can you share that information?

**Comment by patrick-rodgers** [comment]
Going to close this - you haven't provided the requested details and we are unable to reproduce any issue with SPFx 1.12.1 and the library. Please open a new issue with details and we can investigate. Thanks!
