### PR TITLE
Fix for nodejs issue introduced in 2.0.9, update to batch error handl…

### LINKED ISSUE #1356: Wrong exception message on the updating/adding opeartions
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.6      ]

Please specify what version(s) of SharePoint you are targeting: [    O365     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
The batch size exceeds 1048576 bytes. I expect exception with the message: _The maximum number of bytes allowed to be read from the stream has been exceeded. After the last read operation, a total of 1063984 bytes has been read from the stream; however a maximum of 1048576 bytes is allowed._ 

### Observed Behavior
However, I'm getting "Invalid response, line 0".
```
Error: Invalid response, line 0
    at Function.8xxP.SPBatch.ParseResponse (batch.js:41)
    at SPBatch.<anonymous> (batch.js:178)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at fulfilled (tslib.es6.js:70)
```

### Steps to Reproduce
Try to update Note field with large content.

Thank you for your feedback!

### LINKED ISSUE #1358: Error: Cannot find module '@pnp/sp/files' -- after upgrade 2.0.8 -> 2.0.9
### Category
- [x] Bug

### Version

Please specify what version of the library you are using: [ 2.0.9 ]

Please specify what version(s) of SharePoint you are targeting: [ SP online  ]

node.js: 12.18.0

typescript: 4.0.2

OS: latest Windows 10

### Expected / Desired Behavior / Question
following code can be executed
```ts
import { SPFetchClient } from '@pnp/nodejs-commonjs';
import { sp } from '@pnp/sp-commonjs';

export function initializeSp(): void {
	sp.setup({
		sp: {
			fetchClientFactory: () => {
				return new SPFetchClient('APP_SP_SITE_URL', 'APP_LEGACY_SP_CLIENT_ID', 'APP_LEGACY_SP_CLIENT_SECRET');
			},
		},
	});
}
```

### Observed Behavior
```
C:\test\src>npm start

> nmapi@0.0.4-dev start C:\test
> npx tsc && node dist/app.js

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '@pnp/sp/files'
Require stack:
- C:\test\node_modules\@pnp\nodejs-commonjs\sp-extensions\stream.js
- C:\test\node_modules\@pnp\nodejs-commonjs\sp-extensions\index.js
- C:\test\node_modules\@pnp\nodejs-commonjs\index.js
- C:\test\dist\api\news\spConnector.js
- C:\test\dist\app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._resolveFilename (C:\test\node_modules\module-alias\index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\test\node_modules\@pnp\nodejs-commonjs\sp-extensions\stream.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\test\\node_modules\\@pnp\\nodejs-commonjs\\sp-extensions\\stream.js',
    'C:\\test\\node_modules\\@pnp\\nodejs-commonjs\\sp-extensions\\index.js',
    'C:\\test\\node_modules\\@pnp\\nodejs-commonjs\\index.js',
    'C:\\test\\dist\\api\\news\\spConnector.js',
    'C:\\test\\dist\\app.js'
  ]
}
```

### Steps to Reproduce
On the PnPjs version 2.0.8 the procedure initializeSp() can be executed. After upgrading to v2.0.9 the code cannot be executed.

Dependencies:
```json
	"dependencies": {
		"@pnp/nodejs-commonjs": "2.0.9",
		"@pnp/sp-commonjs": "2.0.9",
		"apollo-server-koa": "~2.17.0",
		"dotenv": "~8.2.0",
		"graphql-playground-middleware-koa": "~1.6.19",
		"koa-passport": "~4.1.3",
		"koa-router": "~9.4.0",
		"module-alias": "~2.2.2",
		"passport-azure-ad": "~4.2.1"
	},
	"devDependencies": {
		"@tsconfig/node12": "~1.0.7",
		"@types/dotenv": "~8.2.0",
		"@types/koa-passport": "~4.0.2",
		"@types/koa-router": "~7.4.1",
		"@types/passport-azure-ad": "~4.0.7",
		"@typescript-eslint/eslint-plugin": "^3.10.1",
		"@typescript-eslint/parser": "^3.10.1",
		"del": "~5.1.0",
		"eslint": "^7.7.0",
		"eslint-plugin-jsdoc": "~30.3.0",
		"gulp": "~4.0.2",
		"gulp-zip": "~5.0.2",
		"husky": "~4.2.5",
		"object-assign": "~4.1.1",
		"typescript": "^4.0.2"
	}
```
tsconfig.json:
```json
{
	"extends": "@tsconfig/node12/tsconfig.json",
	"compilerOptions": {
		"esModuleInterop": false,
		"allowSyntheticDefaultImports": true,
		"incremental": true,
		"moduleResolution": "node",
		"listEmittedFiles": true,
		"locale": "en-us",
		"outDir": "dist",
		"baseUrl": ".",
		"paths": {
			"$/*": ["src/*"],
		},
		"sourceMap": true,
	},
}
```

### LINKED ISSUE #1361: Incorrect Reference in @pnp/nodejs-commonjs
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.9   ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

### Expected / Desired Behavior / Question
Using nodejs (e.g. gulp) via commonjs packages es import/export should not be occuring causing breaking issue.

### Observed Behavior
Using @pnp/nodejs-commonjs package references @pnp/sp instead of @pnp/sp-commonjs in stream.js. Causes import "../folder" error when executing through node.

### Steps to Reproduce
Open @pnp/nodejs-common/sp-extensions/stream.js
See: var files_1 = require("@pnp/sp/files"); 
Should be: var files_1 = require("@pnp/sp-commonjs/files");

### PR DESCRIPTION
**Pull request by patrick-rodgers**
…ing, change to extension impl

#### Category
- [X] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [X] Documentation update?

#### Related Issues

fixes #1358
fixes #1361
fixes #1356

#### What's in this Pull Request?

- update to include .map files in packages
- update to docs for nodejs sp extensions
- update how batch error handling is done
- fix for nodejs-commonjs error in 2.0.9
- updates how extensions are managed when extending a factory

### CODE REVIEW

**Comment by SaadKnowIT** [comment]
If using SPFx 1.4.1 and wanting to use PnPjs V2, this version and all above cause alot of warninings like these:
image

PnPJs Version 2.0.9 works fine without any warnings.

I am guessing that "update to include .map files in packages" i causing the warnings above. How can i fix those if i want to use version newer than 2.0.9?
