### ISSUE TITLE
Error after upgrade to 1.2.3

### ISSUE THREAD

**Issue by bva999** [pnp/pnpjs#288]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.3 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
I use SharePoint Framework 1.6.0. After upgrade @pnp/pnpjs from 1.2.2 to 1.2.3 I get the following error: 
**error TS90010: Type 'List' is not assignable to type 'List'. Two different types with this name exist, but
they are unrelated.**

### Steps to Reproduce
npm update @pnp/pnpjs
gulp build

**Comment by bva999** [comment]
Want to add that after downgrade to 1.2.2 the error disappears
