### PR TITLE
Update adalcertificatefetchclient.ts

### PR DESCRIPTION
**Pull request by cebud**
Fix importing NodeFetchClient. It cause a problem in published package file 'nodejs.es5.umd.js'. (there is generated require('.')...). 

During running my application JEST tests appears error (it was working with previous version 1.3.2):
Cannot find module '.' from 'nodejs.es5.umd.js'

#### Category
- [X ] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### What's in this Pull Request?

Fix importing NodeFetchClient

### CODE REVIEW

**Comment by cebud** [comment]
Related to issue https://github.com/pnp/pnpjs/issues/726

**Comment by robertbullen** [comment]
Thanks @cebud!

**Comment by patrick-rodgers** [comment]
Thanks! Appreciate you helping us out!
