### ISSUE TITLE
RxJS Observable is not working in new version of PnP along with SPFx 1.10.0

### ISSUE THREAD

**Issue by spvjebaraj** [pnp/pnpjs#1088]
Hi,

I created new SPFx project with the version of 1.10.0. I am using the below code to retrieve the item from site. It was worked in the previous version 1.9.1 with PnP JS version 2.0.2.

Currently new PnP version (2.0.3) is installed and it is not working. Please help me to resolve this issue.

```
public getLibraries<T>(
        selectedFields: string,
        filter: string,
        orderBy: string,
        isAscending: boolean
    ): Observable<T[]> {
        return from(
            sp.web.lists
                .filter(filter)
                .select(selectedFields)
                .orderBy(orderBy, isAscending)
                .get()
        ).pipe(
            map((res: T[]) => {
                return res;
            })
        );
    }
```

I am getting the error as "error TS2345: Argument of type 'OperatorFunction<T[], T[]>' is not assignable to parameter of type 'OperatorFunction<T, T[]>'".

**Comment by patrick-rodgers** [comment]
Are you including the right [selective imports](https://pnp.github.io/pnpjs/concepts/selective-imports/) or using the [all preset](https://pnp.github.io/pnpjs/concepts/selective-imports/#sp)?

**Comment by spvjebaraj** [comment]
I am using all/preset.
import { sp } from "@pnp/sp/presets/all";

**Comment by simonagren** [comment]
@spvjebaraj many of these times where you get a collision, it's because of an auto import from the wrong package. 
Could you share the repo maybe?

**Comment by spvjebaraj** [comment]
Please find the below repo for your testing.
[https://github.com/spvjebaraj/spfx-rxjs-test](url)

Service file is referred in ListDataService.ts which resides in Services folder. Kindly check it and let me know the updates. If I changed to any instead of T[] in the line number 27, it is working.

It was worked in the previous versions. Why it is not working in this version?

**Comment by spvjebaraj** [comment]
Any update and solution on this?

**Comment by patrick-rodgers** [comment]
I don't think this is an issue with the library but rather the typings you are trying to use. OperatorFunction isn't anything in our library. Maybe the problem is that you have getLibraries defined as <T> and are returning something that is T[]? I don't know rxjs well enough to know for sure. Going to close this issue as non-library.
