### ISSUE TITLE
Build error "node_modules/@pnp/sp/webs/...: error TS1005: '(' expected." when migrating to 2.0.3

### ISSUE THREAD

**Issue by Sartor87** [pnp/pnpjs#1114]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.3]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
Expected to build the solution after migrating to the latest. Types errors are thrown

### Observed Behavior
We've updated to the latest version of PnP (2.0.3) according to the procedure: removed package-lock, removed @pnp folder from node_modules, updated the references in packages.json, ran npm i

The following errors occur (multiple times):
Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(125,27): error TS1110: Type expected.
Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(125,85): error TS1005: '(' expected.

All of types.d.ts scripts in @pnp/sp sub folders.

We've tried to update the typescript version in package-lock file as well (according to https://pnp.github.io/pnpjs/SPFx-on-premises/) without success.

Also, updated all the code according to the breaking changes.

Also, updated even json files' $schema property (from https://dev.office.com/json-schemas/spfx/* to https://developer.microsoft.com/json-schemas/spfx/*)

### Steps to Reproduce

0. All of the below is used with Waldek Mastykarz docker spfx image
1. Create a project with SPFX v. 
2. Install old version of PnP (below 2.0.0)
3. Go through the upgrade process
4. Check for the erros
5. Creating a project from scratch without going through the migration steps works fine

For the sake of simplicity, attached is the latest package.json contents:

```json
{
  "name": "helloWorld",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-lodash-subset": "1.10.0",
    "@microsoft/sp-office-ui-fabric-core": "1.10.0",
    "@microsoft/sp-webpart-base": "1.10.0",
    "@pnp/common": "^2.0.3",
    "@pnp/odata": "^2.0.3",
    "@pnp/sp": "^2.0.3",
    "@types/es6-promise": "3.3.0",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": "1.13.1",
    "react": "15.6.2",
    "react-dom": "15.6.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.10.0",
    "@microsoft/sp-module-interfaces": "1.10.0",
    "@microsoft/sp-webpart-workbench": "1.10.0",
    "tslint-microsoft-contrib": "~5.0.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}
```

**Comment by koltyakov** [comment]
No need installing `@pnp/common` and `@pnp/odata` explicitly, just `@pnp/sp` is enough in v2.
Regarding the error, `skipLibCheck` in `tsconfig.json` should help. Please [see more](https://github.com/pnp/pnpjs/issues?q=skipLibCheck).

**Comment by patrick-rodgers** [comment]
Going to close this as resolved, if you are still having trouble please open a new issue and ref this one so we can follow up. Thanks
